export const ActionTypes = {
  // auth
  REQUESTLOGIN: "REQUESTLOGIN",
  REQUESTSIGNUP: "REQUESTSIGNUP",
  REQUESTLOGOUT: "REQUESTLOGOUT",
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  AUTHERROR: "AUTHERROR",
  // user details
  REQUEST_API: "REQUEST_API",
  ERROR: "ERROR",
  SET_USERS: "SET_USERS",
  UPDATE_PAGE: "UPDATE_PAGE",
  CLEAN_DATA: "CLEAN_DATA",
  SELECTED_USER: "SELECTED_USER",
  // saga
  REQUEST_API_ASYNC: "REQUEST_API_ASYNC",
};
